port 1194
proto udp
dev tun
topology subnet
server 10.8.0.0 255.255.255.0
server-ipv6 fd88:88:88::/64
push "redirect-gateway def1 ipv6"
push "dhcp-option DNS 10.8.0.1"
push "block-outside-dns"
ca /var/lib/veyl/ca.crt
cert /var/lib/veyl/server.crt
key /var/lib/veyl/server.key
dh none
tls-crypt /var/lib/veyl/tls-crypt.key
crl-verify /var/lib/veyl/crl.pem
remote-cert-tls client
tls-version-min 1.2
data-ciphers AES-256-GCM:CHACHA20-POLY1305
auth SHA256
keepalive 10 60
max-clients 250
user nobody
group nogroup
persist-key
persist-tun
verb 0
mute-replay-warnings
management /run/veyl/mgmt unix
