server:
    interface: 10.8.0.1
    ip-freebind: yes
    access-control: 10.8.0.0/24 allow
    access-control: fd88:88:88::/64 allow
    do-ip6: yes
    use-syslog: no
    logfile: ""
    verbosity: 0
    log-queries: no
    log-replies: no
    log-servfail: no
    hide-identity: yes
    hide-version: yes
    qname-minimisation: yes
    prefetch: yes
    cache-min-ttl: 60
    harden-glue: yes
    harden-dnssec-stripped: yes
